name: puck
version: 0.1.0.0
github: "lpil/puck"
license: AGPL-3.0-only
author: "Louis Pilfold"
maintainer: "louis@lpil.uk"
copyright: "2019 - present Louis Pilfold"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis: Short description of your package
# category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/lpil/puck#readme>

ghc-options:
  - -Wall
  - -Wno-type-defaults

default-extensions:
  - OverloadedStrings
  - NoImplicitPrelude
  - DuplicateRecordFields

dependencies:
  - base >= 4.7 && < 5
  - protolude
  - warp
  - wai
  - wai-extra

library:
  source-dirs: src
  dependencies:
    - lucid
    - http-types
    - bytestring
    - wai-middleware-static

executables:
  puck-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - puck

tests:
  puck-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - puck
      - tasty
      - tasty-wai
      - tasty-hunit
      - tasty-discover
